// GET /.well-known/assetlinks.json  (served here via a vercel.json rewrite)
// Digital Asset Links: lets an installed Android app (a TWA — Trusted Web Activity) prove it owns
// this domain, which is what removes the browser URL bar so it looks like a real native app.
// Served from a function rather than a static file so it's always delivered as application/json.
//
// You do NOT edit this file to configure it — set these in Vercel → Settings → Environment Variables,
// then redeploy. Two ways, pick whichever is easier:
//
//   EASIEST — paste the whole file PWABuilder/Bubblewrap generates for you:
//     ASSETLINKS_JSON = <the exact JSON array they give you>
//
//   OR provide the pieces and we assemble it (good for a single app):
//     ANDROID_PACKAGE_NAME       the app id you chose, e.g. "app.slickchart.twa"
//     ANDROID_CERT_FINGERPRINTS  the SHA-256 signing-cert fingerprint (colon-separated hex).
//                                Comma-separate if you have more than one (upload key + Play signing).
//     Find it in PWABuilder's download, or Play Console → App integrity → App signing.
//
// Until one of these is set, this returns a structurally-valid file with an empty fingerprint list
// (verification simply stays "pending" — nothing breaks, the URL bar just shows until you fill it in).
export default function handler(req, res) {
  res.setHeader('Content-Type', 'application/json; charset=utf-8');
  res.setHeader('Cache-Control', 'public, max-age=300');

  // 1) Full override: return exactly what the build tool generated, if provided.
  const raw = process.env.ASSETLINKS_JSON;
  if (raw && raw.trim()) {
    try { res.status(200).send(JSON.stringify(JSON.parse(raw))); return; }
    catch (e) { /* fall through to the assembled version if the pasted JSON is malformed */ }
  }

  // 2) Assemble from the individual pieces (single-app common case).
  const pkg = (process.env.ANDROID_PACKAGE_NAME || 'app.slickchart.twa').trim();
  const fingerprints = String(process.env.ANDROID_CERT_FINGERPRINTS || '')
    .split(',').map(s => s.trim()).filter(Boolean);
  const body = [{
    relation: ['delegate_permission/common.handle_all_urls'],
    target: { namespace: 'android_app', package_name: pkg, sha256_cert_fingerprints: fingerprints }
  }];
  res.status(200).send(JSON.stringify(body, null, 2));
}
